apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: bmf-serapiondev-com-tls
spec:
  secretName: bmf-serapiondev-com
  issuerRef: 
    name: bmf-cert-staging
    kind: ClusterIssuer
  commonName: bmf.serapiondev.com
  dnsNames:
    - bmf.serapiondev.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bmf.serapiondev.com
