apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: registry.gitlab.com/brand-master-flash/bmf-web/bmf-backend:v18
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URL
              value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/serapion?replicaSet=rs0"
            - name: APP_SECRET
              value: "1b5c2f89543c1d86c94700c93b988ad3"
            - name: PAYPAL_REDIRECT_URL
              value: "https://bmf-serapiondev.com/api/v1/payment-success"
            - name: INSTAGRAM_REDIRECT_URL
              value: "https://bmf-serapiondev.com/api/v1/auth/instagram/callback"
      imagePullSecrets:
      - name: regcred
